CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'QC_MEMBER',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_public_id UNIQUE (public_id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE INDEX idx_users_status ON users(status);

CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_email_verification_tokens_public_id UNIQUE (public_id),
    CONSTRAINT uk_email_verification_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_email_verification_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens(user_id);
CREATE INDEX idx_email_verification_tokens_expires_at ON email_verification_tokens(expires_at);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_password_reset_tokens_public_id UNIQUE (public_id),
    CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    evaluation_scope TEXT,
    retention_days INTEGER DEFAULT 30,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_projects_public_id UNIQUE (public_id),
    CONSTRAINT fk_projects_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_projects_created_by ON projects(created_by);
CREATE INDEX idx_projects_status ON projects(status);

CREATE TABLE target_api_connectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    raw_curl TEXT,
    protocol VARCHAR(50) NOT NULL DEFAULT 'HTTP',
    method VARCHAR(20) NOT NULL,
    base_url TEXT,
    path TEXT,
    url TEXT NOT NULL,
    headers_json JSONB,
    query_params_json JSONB,
    path_params_json JSONB,
    body_type VARCHAR(50) NOT NULL DEFAULT 'RAW_JSON',
    body_template_json JSONB,
    body_template_text TEXT,
    auth_type VARCHAR(50) NOT NULL DEFAULT 'NONE',
    auth_config_json JSONB,
    secret_refs_json JSONB,
    is_streaming BOOLEAN NOT NULL DEFAULT false,
    streaming_type VARCHAR(50),
    streaming_event_selector VARCHAR(255),
    response_selector VARCHAR(255) NOT NULL DEFAULT '$.answer',
    response_format VARCHAR(50) NOT NULL DEFAULT 'JSON',
    timeout_seconds INTEGER NOT NULL DEFAULT 60,
    retry_count INTEGER NOT NULL DEFAULT 1,
    active BOOLEAN NOT NULL DEFAULT true,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_target_api_connectors_public_id UNIQUE (public_id),
    CONSTRAINT fk_target_api_connectors_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_target_api_connectors_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_target_api_connectors_project_id ON target_api_connectors(project_id);
CREATE INDEX idx_target_api_connectors_active ON target_api_connectors(active);
CREATE INDEX idx_target_api_connectors_created_by ON target_api_connectors(created_by);

CREATE TABLE business_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_business_requirements_public_id UNIQUE (public_id),
    CONSTRAINT fk_business_requirements_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_business_requirements_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_requirements_project_id ON business_requirements(project_id);
CREATE INDEX idx_requirements_status ON business_requirements(status);
CREATE INDEX idx_requirements_created_by ON business_requirements(created_by);
