CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(512),
    role VARCHAR(50) NOT NULL DEFAULT 'QC_MEMBER',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_public_id UNIQUE (public_id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE INDEX idx_users_status ON users(status);

CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_email_verification_tokens_public_id UNIQUE (public_id),
    CONSTRAINT uk_email_verification_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_email_verification_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens(user_id);
CREATE INDEX idx_email_verification_tokens_expires_at ON email_verification_tokens(expires_at);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_password_reset_tokens_public_id UNIQUE (public_id),
    CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    evaluation_scope TEXT,
    retention_days INTEGER DEFAULT 30,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_projects_public_id UNIQUE (public_id),
    CONSTRAINT fk_projects_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_projects_created_by ON projects(created_by);
CREATE INDEX idx_projects_status ON projects(status);

CREATE TABLE target_api_connectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    raw_curl TEXT,
    protocol VARCHAR(50) NOT NULL DEFAULT 'HTTP',
    method VARCHAR(20) NOT NULL,
    base_url TEXT,
    path TEXT,
    url TEXT NOT NULL,
    headers_json JSONB,
    query_params_json JSONB,
    path_params_json JSONB,
    body_type VARCHAR(50) NOT NULL DEFAULT 'RAW_JSON',
    body_template_json JSONB,
    body_template_text TEXT,
    auth_type VARCHAR(50) NOT NULL DEFAULT 'NONE',
    auth_config_json JSONB,
    secret_refs_json JSONB,
    is_streaming BOOLEAN NOT NULL DEFAULT false,
    streaming_type VARCHAR(50),
    streaming_event_selector VARCHAR(255),
    response_selector VARCHAR(255) NOT NULL DEFAULT '$.answer',

    response_format VARCHAR(50) NOT NULL DEFAULT 'JSON',
    timeout_seconds INTEGER NOT NULL DEFAULT 60,
    retry_count INTEGER NOT NULL DEFAULT 1,
    active BOOLEAN NOT NULL DEFAULT true,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_target_api_connectors_public_id UNIQUE (public_id),
    CONSTRAINT fk_target_api_connectors_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_target_api_connectors_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_target_api_connectors_project_id ON target_api_connectors(project_id);
CREATE INDEX idx_target_api_connectors_active ON target_api_connectors(active);
CREATE INDEX idx_target_api_connectors_created_by ON target_api_connectors(created_by);

CREATE TABLE business_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_business_requirements_public_id UNIQUE (public_id),
    CONSTRAINT fk_business_requirements_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_business_requirements_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_requirements_project_id ON business_requirements(project_id);
CREATE INDEX idx_requirements_status ON business_requirements(status);
CREATE INDEX idx_requirements_created_by ON business_requirements(created_by);

CREATE TABLE datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    generation_prompt TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    source_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    approved_by BIGINT,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_datasets_public_id UNIQUE (public_id),
    CONSTRAINT fk_datasets_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_datasets_created_by
        FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_datasets_approved_by
        FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE INDEX idx_datasets_project_id ON datasets(project_id);
CREATE INDEX idx_datasets_status ON datasets(status);
CREATE INDEX idx_datasets_created_by ON datasets(created_by);

CREATE TABLE test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    dataset_id BIGINT NOT NULL,
    external_id VARCHAR(255),
    question TEXT NOT NULL,
    precondition JSONB,
    ground_truth TEXT,
    metadata_json JSONB,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    sort_order INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_test_cases_public_id UNIQUE (public_id),
    CONSTRAINT fk_test_cases_dataset
        FOREIGN KEY (dataset_id) REFERENCES datasets(id)
);

CREATE INDEX idx_test_cases_dataset_id ON test_cases(dataset_id);
CREATE INDEX idx_test_cases_status ON test_cases(status);
CREATE INDEX idx_test_cases_external_id ON test_cases(external_id);

CREATE TABLE rubrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    current_version INTEGER,
    is_template BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_rubrics_public_id UNIQUE (public_id),
    CONSTRAINT fk_rubrics_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_rubrics_status ON rubrics(status);
CREATE INDEX idx_rubrics_created_by ON rubrics(created_by);
CREATE INDEX idx_rubrics_is_template ON rubrics(is_template);

CREATE TABLE rubric_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    rubric_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    content TEXT,
    output_schema_json TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ,
    CONSTRAINT uk_rubric_versions_public_id UNIQUE (public_id),
    CONSTRAINT uk_rubric_versions_rubric_version UNIQUE (rubric_id, version),
    CONSTRAINT fk_rubric_versions_rubric
        FOREIGN KEY (rubric_id) REFERENCES rubrics(id),
    CONSTRAINT fk_rubric_versions_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_rubric_versions_rubric_id ON rubric_versions(rubric_id);
CREATE INDEX idx_rubric_versions_status ON rubric_versions(status);
CREATE INDEX idx_rubric_versions_created_by ON rubric_versions(created_by);

CREATE TABLE rubric_criteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    rubric_version_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    weight INTEGER NOT NULL DEFAULT 1,
    pass_condition TEXT,
    fail_condition TEXT,
    judge_instruction TEXT NOT NULL,
    metric_key VARCHAR(100) NOT NULL,
    is_critical BOOLEAN NOT NULL DEFAULT false,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_rubric_criteria_public_id UNIQUE (public_id),
    CONSTRAINT uk_rubric_criteria_version_metric_key UNIQUE (rubric_version_id, metric_key),
    CONSTRAINT fk_rubric_criteria_version
        FOREIGN KEY (rubric_version_id) REFERENCES rubric_versions(id)
);

CREATE INDEX idx_rubric_criteria_version_id ON rubric_criteria(rubric_version_id);
CREATE INDEX idx_rubric_criteria_metric_key ON rubric_criteria(metric_key);
CREATE INDEX idx_rubric_criteria_sort_order ON rubric_criteria(sort_order);
