CREATE TABLE review_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    evaluation_result_id BIGINT NOT NULL REFERENCES evaluation_results(id),
    qc_status VARCHAR(50) NOT NULL,
    qc_note TEXT,
    pic_bug_user_id BIGINT REFERENCES users(id),
    reviewed_by BIGINT NOT NULL REFERENCES users(id),
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_review_decisions_public_id UNIQUE (public_id),
    CONSTRAINT uk_review_decisions_result_id UNIQUE (evaluation_result_id)
);

CREATE INDEX idx_review_decisions_qc_status ON review_decisions(qc_status);
CREATE INDEX idx_review_decisions_pic_bug_user_id ON review_decisions(pic_bug_user_id);
