CREATE TABLE export_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL REFERENCES projects(id),
    evaluation_run_id BIGINT NOT NULL REFERENCES evaluation_runs(id),
    job_id BIGINT REFERENCES jobs(id),
    file_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    file_path TEXT,
    file_name VARCHAR(255),
    error_message TEXT,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ready_at TIMESTAMPTZ,
    CONSTRAINT uk_export_files_public_id UNIQUE (public_id)
);

CREATE INDEX idx_export_files_run_id ON export_files(evaluation_run_id);
CREATE INDEX idx_export_files_status ON export_files(status);
CREATE INDEX idx_export_files_project_id ON export_files(project_id);
