CREATE TABLE target_api_connectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    raw_curl TEXT,
    protocol VARCHAR(50) NOT NULL DEFAULT 'HTTP',
    method VARCHAR(20) NOT NULL,
    base_url TEXT,
    path TEXT,
    url TEXT NOT NULL,
    headers_json JSONB,
    query_params_json JSONB,
    path_params_json JSONB,
    body_type VARCHAR(50) NOT NULL DEFAULT 'RAW_JSON',
    body_template_json JSONB,
    body_template_text TEXT,
    auth_type VARCHAR(50) NOT NULL DEFAULT 'NONE',
    auth_config_json JSONB,
    secret_refs_json JSONB,
    is_streaming BOOLEAN NOT NULL DEFAULT false,
    streaming_type VARCHAR(50),
    streaming_event_selector VARCHAR(255),
    response_selector VARCHAR(255) NOT NULL DEFAULT '$.answer',
    response_format VARCHAR(50) NOT NULL DEFAULT 'JSON',
    timeout_seconds INTEGER NOT NULL DEFAULT 60,
    retry_count INTEGER NOT NULL DEFAULT 1,
    active BOOLEAN NOT NULL DEFAULT true,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_target_api_connectors_public_id UNIQUE (public_id),
    CONSTRAINT fk_target_api_connectors_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_target_api_connectors_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_target_api_connectors_project_id ON target_api_connectors(project_id);
CREATE INDEX idx_target_api_connectors_active ON target_api_connectors(active);
CREATE INDEX idx_target_api_connectors_created_by ON target_api_connectors(created_by);
