-- connector_secrets: stores encrypted API keys / tokens per connector
CREATE TABLE connector_secrets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id BIGINT NOT NULL,
    secret_key VARCHAR(255) NOT NULL,
    encrypted_value TEXT NOT NULL,
    masked_value VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_connector_secrets_connector
        FOREIGN KEY (connector_id) REFERENCES target_api_connectors(id) ON DELETE CASCADE,
    CONSTRAINT uk_connector_secrets_connector_key UNIQUE (connector_id, secret_key)
);

CREATE INDEX idx_connector_secrets_connector_id ON connector_secrets(connector_id);
