CREATE TABLE business_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_business_requirements_public_id UNIQUE (public_id),
    CONSTRAINT fk_business_requirements_project
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_business_requirements_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_requirements_project_id ON business_requirements(project_id);
CREATE INDEX idx_requirements_status ON business_requirements(status);
CREATE INDEX idx_requirements_created_by ON business_requirements(created_by);
