CREATE TABLE red_team_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    project_id BIGINT NOT NULL REFERENCES projects(id),
    target_api_connector_id BIGINT NOT NULL REFERENCES target_api_connectors(id),
    judge_model_id BIGINT REFERENCES judge_models(id),
    job_id BIGINT REFERENCES jobs(id),
    name VARCHAR(255) NOT NULL,
    purpose TEXT,
    plugins_json JSONB,
    strategies_json JSONB,
    num_tests INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    total_cases INTEGER NOT NULL DEFAULT 0,
    passed_cases INTEGER NOT NULL DEFAULT 0,
    failed_cases INTEGER NOT NULL DEFAULT 0,
    error_cases INTEGER NOT NULL DEFAULT 0,
    artifact_dir TEXT,
    error_message TEXT,
    created_by BIGINT NOT NULL REFERENCES users(id),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_red_team_runs_public_id UNIQUE (public_id)
);

CREATE INDEX idx_red_team_runs_project_id ON red_team_runs(project_id);
CREATE INDEX idx_red_team_runs_status ON red_team_runs(status);
CREATE INDEX idx_red_team_runs_created_at ON red_team_runs(created_at);
